### ISSUE TITLE
"ERROR ROS Dep database not updated" with --user

### ISSUE THREAD

**Issue by qingbyin** [osrf/rocker#209]
Steps to reproduce:
```
$ rocker --user osrf/ros:noetic-desktop-full
$ roswtf
```

The error:
```
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
No package or stack in the current directory
================================================================================
Static checks summary:

Found 1 error(s).

ERROR ROS Dep database not updated: Please update rosdep database with 'rosdep update'.
================================================================================
```

**Comment by tfoote** [comment]
This is expected. The image does not have the rosdep database included because by the time you use the image the rosdep database is expected to be out of date. Before you invoke rosdep to resolve or install dependencies, you should do a rosdep update.

If you just do a rosdep update that will resolve the error. 

Also if you use the --home --user options you'll get the database from your host.
